[project]
name = "kokoro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jantzmorgan", email = "jantzswag@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.3",
    "kokoro-onnx>=0.5.0",
    "numpy>=2.5.2",
    "sounddevice>=0.5.5",
    "soundfile>=0.14.0",
]

[project.scripts]
kokoro = "kokoro:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
